import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import ActiveSectionContextProvider from "@/context/active-section-context";
import Footer from "@/components/footer";
import { Toaster } from "sonner";
import ThemeSwitch from "@/components/theme-switch";
import ThemeContextProvider from "@/context/theme-context";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Personal Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/fa.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative 
  bg-[var(--color-PrimaryBg)] text-[var(--color-PrimaryText)]`}
        suppressHydrationWarning={true}
      >

        <div
          className="absolute top-[-6rem] right-[11rem] h-[31.25rem] w-[31.25rem]
    rounded-full blur-[10rem] sm:w-[68.75rem] -z-10 
    opacity-25 bg-[#4EF5C8]/40 dark:bg-[#4EF5C8]/20"
        ></div>


        <div
          className="absolute top-[-1rem] left-[-35rem] h-[31.25rem] w-[50rem]
    rounded-full blur-[10rem] sm:w-[68.75rem] md:left-[-33rem]
    lg:left-[-28rem] xl:left-[15rem] 2xl:left-[-5rem] -z-10
    opacity-20 bg-[#1E2D29]/40 dark:bg-[#0D1B2A]/40"
        ></div>
 <ThemeContextProvider>


   <ActiveSectionContextProvider>
          <Header />
          {children}
        
          <Footer />  
          <Toaster
            position="top-center"
            richColors
            toastOptions={{
              style: {
                background: "var(--color-CardBg)",
                color: "var(--color-PrimaryText)",
                border: "1px solid var(--color-Border)",
              },
              classNames: {
                success: "bg-[var(--color-Accent)] text-[var(--color-BtnText)]",
                error: "bg-red-500 text-white",
                info: "bg-[var(--color-AccentMuted)] text-[var(--color-PrimaryText)]",
              },
            }}
          />
          <ThemeSwitch />
        </ActiveSectionContextProvider>
 </ThemeContextProvider>

       





      </body>
    </html>
  );
}
